### ISSUE TITLE
Can't get Product.Name in search results 

### ISSUE THREAD

**Issue by nikkofu** [dinistavares/go-prestashop-api#1]
I'm testing the api with default prestashop 8.1.3

	params := &prestashop.ServiceListParams{
		Display: &prestashop.ServiceListDisplay{
			"id",
			"name",
			"price",
		},
	}

	list, response, err := client.Product.List(params)
	if err != nil {
		slog.Error("prestashop", "err", err.Error())
		return
	}

	slog.Info("prestashop", "response", response)

	for _, v := range *list {
		//slog.Info("prestashop", "product", v)
		slog.Info("prestashop", "product", fmt.Sprintf("id: %d, name: %s, price: %s", v.ID, v.Name, v.Price))
	}

Then I got these:

2024/01/12 22:33:48 INFO prestashop product="id: 1, name: , price: 23.900000"
2024/01/12 22:33:48 INFO prestashop product="id: 2, name: , price: 35.900000"
2024/01/12 22:33:48 INFO prestashop product="id: 16, name: , price: 12.900000"

Please help, thanks,

nikkofu@gmail.com

**Comment by dinistavares** [comment]
Hello!

Initially I created this using the JSON output from the API and the response was different but I am experimenting using XML data only. I made a patch for the products resource only on `go-prestashop-api@v0.1.1` you can try access the name using `v.Name.Language` 

I'll update the other resources next week, but I may change this in the future and revert to using JSON outputs from the API.

**Comment by nikkofu** [comment]
thanks for solving this so quickly.

hoping for the new features.
