### ISSUE TITLE
Suggestion: Add IDLang to the Query Params to get the right data

### ISSUE THREAD

**Issue by nikkofu** [dinistavares/go-prestashop-api#2]
If possible, change the struct like this:

type ServiceListParams struct {
	...
	IDLang int
}

Then the client will return the list/detail data like:
lang = 1 & id = 1:  p.Name => "Hummingbird printed t-shirt"
lang = 2 & id = 1:  p.Name => "تيشيرت بطبعة الطائر الطنان"

Fill free if you have any better solution. 

:)

**Comment by nikkofu** [comment]
I'm now using for+range func to get the text with one language,

I think this is a simple way to do,

type ProductLanguageData struct {
	Language *[]ProductLanguage `xml:"language,omitempty" json:"language,omitempty"`
	//Text string,  add for language hooks
}

// utils
func StrToInt(s string) int {
	val, err := strconv.Atoi(s)
	if err != nil {
		return 0
	}
	return val
}

func GetLanguageText(idLang int, Language *[]prestashop.ProductLanguage) string {
	if Language != nil {
		for _, v := range *Language {
			if utils.StrToInt(v.ID) == idLang {
				return v.Text
			}
		}
	}
	return ""
}

If I put some id lang value in the query params, then the response will add hook to return what I need, 

then I can get this in everywhere

p.Name.Language  for range  .Text  ==>  p.Name.Text

**Comment by dinistavares** [comment]
Hello!

Thanks! I will add some helper functions like this to get product names by language ID + default languages. (I will consider the first language as the default language)

**Comment by dinistavares** [comment]
Hey!

I added two new helper functions: 
* GetDefaultLanguageValue
* GetLanguageValueByID 

to get languages by ID or the default language text
