### ISSUE TITLE
Customer struct ID *int ?

### ISSUE THREAD

**Issue by nikkofu** [dinistavares/go-prestashop-api#4]
Testing the find by email service, got these result:

2024/01/25 11:19:54 INFO prestashop "customer by email"="&{ID:0xc000014c08 IDDefaultGroup:3 IDLang:3 NewsletterDateAdd:2024-01-25 12:14:56 ..."

type Customer struct {
	ID                       *int 
...
}

Would the ID be changed to int better than *int?

Thanks

**Comment by nikkofu** [comment]
closed

**Comment by dinistavares** [comment]
Yes, that was a mistake! I'll likely me making more changes in the future. :)
